# Generated by Django 4.0.4 on 2022-05-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain, baidu.com')),
            ],
        ),
    ]
