# Generated by Django 4.0.4 on 2022-05-30 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('port', models.CharField(max_length=30, verbose_name='Port')),
                ('service', models.CharField(max_length=200, verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='AssetSubDomain',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('subdomain', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Subdomain')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('title', models.CharField(max_length=200, verbose_name='Web Title')),
                ('fingerprint', models.CharField(max_length=200, verbose_name='Web Fingerprint')),
                ('waf', models.CharField(max_length=100, verbose_name='WAF Fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='AssetUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('api_name', models.CharField(max_length=200, verbose_name='API Name')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('subdomain', models.CharField(max_length=200, verbose_name='SubDomain')),
                ('post_data', models.CharField(max_length=1000, verbose_name='Post Data')),
                ('request_data', models.TextField(verbose_name='Request Data')),
                ('response_data', models.TextField(verbose_name='Response Data')),
                ('tag_1', models.CharField(max_length=200, verbose_name='Tag 1')),
                ('tag_2', models.CharField(max_length=200, verbose_name='Tag 2')),
                ('tag_3', models.CharField(max_length=200, verbose_name='Tag 3')),
                ('tag_4', models.CharField(max_length=200, verbose_name='Tag 4')),
                ('tag_5', models.CharField(max_length=200, verbose_name='Tag 5')),
                ('tag_6', models.CharField(max_length=200, verbose_name='Tag 6')),
            ],
        ),
        migrations.RemoveField(
            model_name='assetgroup',
            name='id',
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='desc',
            field=models.TextField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='domain',
            field=models.CharField(max_length=100, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Group Name'),
        ),
    ]
