# Generated by Django 4.0.5 on 2022-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetports_assetsubdomain_asseturls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('ip', models.CharField(max_length=50, verbose_name='IP')),
                ('port', models.CharField(max_length=30, verbose_name='Port')),
                ('service', models.CharField(max_length=200, verbose_name='Service')),
                ('service_info', models.TextField(verbose_name='Service Info')),
            ],
        ),
        migrations.CreateModel(
            name='AssetUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('api_name', models.CharField(max_length=200, verbose_name='API Name')),
                ('uri', models.CharField(max_length=500, verbose_name='URI')),
                ('subdomain', models.CharField(max_length=200, verbose_name='HOST')),
                ('post_data', models.CharField(max_length=1000, verbose_name='Post Data')),
                ('request_data', models.TextField(verbose_name='Request Data Raw')),
                ('response_data', models.TextField(verbose_name='Response Data Raw')),
                ('iframe_fingerprint', models.CharField(max_length=200, verbose_name='Iframe')),
                ('params_json', models.CharField(max_length=200, verbose_name='Params')),
                ('ret_code', models.IntegerField(verbose_name='RetCode')),
                ('method', models.CharField(max_length=50, verbose_name='Method')),
                ('referer', models.CharField(max_length=200, verbose_name='Referer')),
                ('cookie', models.CharField(max_length=500, verbose_name='Cookie')),
                ('res_info', models.CharField(max_length=200, verbose_name='Response Info')),
            ],
        ),
        migrations.CreateModel(
            name='AttackSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('assert_name', models.CharField(max_length=100, verbose_name='Assert Name')),
                ('vuln_name', models.CharField(max_length=500, verbose_name='Vuln Name')),
                ('vuln_level', models.IntegerField(verbose_name='Vuln Level')),
                ('poc_info', models.TextField(verbose_name='Poc Info')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Group Name')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AssetPorts',
        ),
        migrations.DeleteModel(
            name='AssetUrls',
        ),
        migrations.RemoveField(
            model_name='assetgroup',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='assetgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='domain_name',
            field=models.CharField(default=111, max_length=50, primary_key=True, serialize=False, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='target_name',
            field=models.CharField(default=2222, max_length=50, verbose_name='Group Name'),
            preserve_default=False,
        ),
    ]
